/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoProjetsRouteImport } from './routes/video-projets'
import { Route as IndexRouteImport } from './routes/index'

const VideoProjetsRoute = VideoProjetsRouteImport.update({
  id: '/video-projets',
  path: '/video-projets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/video-projets': typeof VideoProjetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/video-projets': typeof VideoProjetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/video-projets': typeof VideoProjetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/video-projets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/video-projets'
  id: '__root__' | '/' | '/video-projets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideoProjetsRoute: typeof VideoProjetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-projets': {
      id: '/video-projets'
      path: '/video-projets'
      fullPath: '/video-projets'
      preLoaderRoute: typeof VideoProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideoProjetsRoute: VideoProjetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
